server:
  port: 8081

spring:
  application:
    name: cloud-dingtalk-example

  profiles:
    active: dev

  dinger:
    project-id: ${spring.application.name}
    default-dinger: wetalk
    dingers:
      wetalk:
        token-id: 0a0b9279-ac5b-4b95-bb69-e30a9dde286e






